FROM python:3.9-alpine

ENV HOME=/usr/src/app
ENV APP_HOME=$HOME/backend
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR $APP_HOME

RUN pip install --upgrade pip && \
    pip install pipenv

COPY Pipfile .
COPY Pipfile.lock .

RUN pipenv install --system --deploy

COPY .. .

ENTRYPOINT ["/usr/src/app/backend/docker-entrypoint.prod.sh"]
