# Generated by Django 4.2.4 on 2023-08-09 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('amount_of_shows', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Создавать фотографии без просмотров запрещено!')], verbose_name='Колличество показов картинки')),
                ('tags', models.ManyToManyField(related_name='photos', to='photo_contents.tag', verbose_name='Теги фотографии')),
            ],
        ),
    ]
