# Generated by Django 4.2.4 on 2023-08-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='./', verbose_name='Изображение'),
        ),
    ]
