# Generated by Django 4.2.4 on 2023-08-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_contents', '0003_alter_photo_options_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-amount_of_shows',), 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
